fix compile errors with clang
../src/percetto.cc:135:1: error: cannot define or redeclare
'static_state_' here because namespace '' does not enclose namespace
'DataSource<(anonymous namespace)::PercettoDataSource,
perfetto::DefaultDataSourceTraits>'